language: python
python:
- 3.6.2
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE USER saifudevuser PASSWORD 'password';" -U postgres
- psql -c "ALTER USER saifudevuser CREATEDB;" -U postgres
- psql -c "CREATE DATABASE saifudev OWNER saifudevuser;" -U postgres
script:
- python manage.py migrate
- python manage.py test core
deploy:
  provider: heroku
  api_key:
    secure: fNQ/Ni1TRT0OZS8G4wV42ecI3wcG8CJ66uH2R9a5+nYFzK5nAVf3pkgz+PZJ/I1oSfaHc0PZlRaC7ldXzEc8crrSJA9BiAcSWbdW2qYVPTjMI37SVlvbV+NAQgWYdWp8zFtRnywHL07XrhaOh7u6kYLubZPoLGYGk/TRoVXL4URAsZnaa/L02bG33EcjdiUGtX82Sh3xeqyL+XBvdYcr6X8GM8GJ3pr/+1EPxg7NkD7XdK45+Q60LOBM1+FFtvWB1JV7YTMNm04gjUbobMV+CvmYEuRcO9sUL9cnXDn4B/5845JXWm3P3LtCoq0lyjyQMy823Ce7wKvVY463UtDp3ZN33/GxsjNAt39yK7JdqvP1ojpCuqQqiZguN2MwHwnOIqHEAeZveSahMqSEvVdyGEJ0lbCwllvuLDyZTgS2uROWMJT757VmaIPEIBk1BbccpWbVVJUj1n3EbX9xQnhtANSDm0mfRb1kYVYYr55akhiBSw6BnpYomSeW/JKWW5Mg4FJLbKOMVDMR9kaTkWDkphzERbO4LzAjTWXIx9xQ945KOyW4w6bFYBbbcKObRv2Loo6OgmGHsj9G+b9nB5ZHy/GugKh8lAsEeIs8h/USiAEUGuO0vNDEDTZEY1MkGhCSlMadmHZLlp7/2P28p4K1p8k20UcHwe7rMAtNk7nhdwk=
  skip_cleanup: true
  on: develop
  app:
    develop: saifu-api-stg
notifications:
  email: false
  slack:
    rooms:
      secure: nwynLXkajg1L5ww7sH9DpODtWOAHQPrSuz7cBFvhe2y3UOlVfPoFMzFN0l+cFr3gLhNsn6L/LXBB8jBGZn3yWYF6GH2Hu/ljDKbjPPgIt3Ttl7mD3wPPXoRzkUBkMSEuEYY+2tip1SBTTNofUJJli2MLCkRa26IngnaoSrfFlT63g7FMh+y3v3oLmM5WJ4HNw1jUJ8p/AZgh874lzGwjku/5VLoPTZhFXjLNtQmw3+/Xa+2l0nBmMVC8Nlw6X0F5uz81GxCskRf/jcQSe3QbVMCOpBoEwIQhrO4FuyW08pyUIDeN+N1ycKxGQvUFFlKqC8grqrUGEaiUEKM1Z/jjbwKbyW/NKBH5EYsTIsnPaDPryo6A+j5eGJNUYsFpruxnjdEvVcnGR+pw+jW6DV25vFulGZS7dcKtNKdVg6a7RMdWKC8o0EM/pSiJO2pfzxqyWSEuZ0nXGFvJ0EwjJ9O+fu9HZRqFe2ujqn3NGVqH86rg4++KBL4HlP3LGG48zbBI79Ez4UqgSpv3JkEXFsT0rIUiqRyenwbkcHURQYbXnRpBdTxxoqADcUuT15yOQT0IukWRHDnTp9lON9bQvI9WL9P1qlYQftGEpcXENvrm85KB3wSN5hBUgru69AuqA9wQqaT9FeE9CYAMOFC3nShwKofhivy5RAewVpOruUWYcyw=
