language: python
python:
- 3.6.2
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE USER saifudevuser PASSWORD 'password';" -U postgres
- psql -c "ALTER USER saifudevuser CREATEDB;" -U postgres
- psql -c "CREATE DATABASE saifudev OWNER saifudevuser;" -U postgres
script:
- python manage.py migrate
- python manage.py test core
deploy:
  provider: heroku
  api_key:
    secure: fNQ/Ni1TRT0OZS8G4wV42ecI3wcG8CJ66uH2R9a5+nYFzK5nAVf3pkgz+PZJ/I1oSfaHc0PZlRaC7ldXzEc8crrSJA9BiAcSWbdW2qYVPTjMI37SVlvbV+NAQgWYdWp8zFtRnywHL07XrhaOh7u6kYLubZPoLGYGk/TRoVXL4URAsZnaa/L02bG33EcjdiUGtX82Sh3xeqyL+XBvdYcr6X8GM8GJ3pr/+1EPxg7NkD7XdK45+Q60LOBM1+FFtvWB1JV7YTMNm04gjUbobMV+CvmYEuRcO9sUL9cnXDn4B/5845JXWm3P3LtCoq0lyjyQMy823Ce7wKvVY463UtDp3ZN33/GxsjNAt39yK7JdqvP1ojpCuqQqiZguN2MwHwnOIqHEAeZveSahMqSEvVdyGEJ0lbCwllvuLDyZTgS2uROWMJT757VmaIPEIBk1BbccpWbVVJUj1n3EbX9xQnhtANSDm0mfRb1kYVYYr55akhiBSw6BnpYomSeW/JKWW5Mg4FJLbKOMVDMR9kaTkWDkphzERbO4LzAjTWXIx9xQ945KOyW4w6bFYBbbcKObRv2Loo6OgmGHsj9G+b9nB5ZHy/GugKh8lAsEeIs8h/USiAEUGuO0vNDEDTZEY1MkGhCSlMadmHZLlp7/2P28p4K1p8k20UcHwe7rMAtNk7nhdwk=
  skip_cleanup: true
  on: develop
  app:
    develop: saifu-api-stg
notifications:
  email: false
  slack:
    rooms:
      secure: nAVYFGxtRYe8MHWs1uGI85G145ZCqC4kpg9qVWJq8ifJZZ6cKi4wzHN29UvV7OtTwGV1Nj3jxEMdpqjkSRRJb0Ap0JSnv8x2h+1/dfv3C3bcDJFQ2J1exkIYvaTA79Sh+I0JKvV1dVaxh04aM3G9SNFMHdslrQtO9A1hPKGz8PmnduTeNgN4+/XQ4ebTFDSfFvEuFms31Fmx0ZhW9mcWUQ6dRdd4l9psIg0vyTAUfx6zTAJ7hcpcznblJ7ptsAloSKhxacibiwGooC7ZW7N+aypdM5b3FJc11KsJrEed2hYiG0XzD2LDjeyKzAr7FT/eEODvKQzMUT1sRe55UaxIyCgf98hm3Um06FMYIeEVT2sJpdXhEFAqpI8g1axSsmk1d0ou4Jj+C6ZmlFyxMIObpeKecnaJcDP6Nt/WH97qqfQiiViP5JNGB5xFHkHDZMxuYLeJd3p/Zwdt+waCDGn7iQpG/Lf5MgIaf3gPO7jZMrZOWQ49U840BqKt7Qq9Uawukxgsbp1utzOxDN/vWacx8NZdGSZvS2MYZbw5qb9klVHnNWwyfkqA99yXLzrwL+jtViHMwzYw8sqA/eIGc9r0XpKLkjJHXFFL0IrgI8aimDqfi+kpXKiHICEpmmnuu8VKSsB2JbZlrHsp2e5oRbrSTBfzAdKJ9Tmk+KAzMDrgrsQ=
