language: python

python:
- 3.6.3

services:
- postgresql

install:
- pip install -r requirements.txt
- pip install coverage
- pip install codecov

before_script:
- psql -c "CREATE USER saifudevuser PASSWORD 'password';" -U postgres
- psql -c "ALTER USER saifudevuser CREATEDB;" -U postgres
- psql -c "CREATE DATABASE saifudev OWNER saifudevuser;" -U postgres

script:
- python manage.py migrate
- coverage run --source=core manage.py test core

after_success:
- codecov

deploy:
  provider: heroku
  api_key:
    secure: fNQ/Ni1TRT0OZS8G4wV42ecI3wcG8CJ66uH2R9a5+nYFzK5nAVf3pkgz+PZJ/I1oSfaHc0PZlRaC7ldXzEc8crrSJA9BiAcSWbdW2qYVPTjMI37SVlvbV+NAQgWYdWp8zFtRnywHL07XrhaOh7u6kYLubZPoLGYGk/TRoVXL4URAsZnaa/L02bG33EcjdiUGtX82Sh3xeqyL+XBvdYcr6X8GM8GJ3pr/+1EPxg7NkD7XdK45+Q60LOBM1+FFtvWB1JV7YTMNm04gjUbobMV+CvmYEuRcO9sUL9cnXDn4B/5845JXWm3P3LtCoq0lyjyQMy823Ce7wKvVY463UtDp3ZN33/GxsjNAt39yK7JdqvP1ojpCuqQqiZguN2MwHwnOIqHEAeZveSahMqSEvVdyGEJ0lbCwllvuLDyZTgS2uROWMJT757VmaIPEIBk1BbccpWbVVJUj1n3EbX9xQnhtANSDm0mfRb1kYVYYr55akhiBSw6BnpYomSeW/JKWW5Mg4FJLbKOMVDMR9kaTkWDkphzERbO4LzAjTWXIx9xQ945KOyW4w6bFYBbbcKObRv2Loo6OgmGHsj9G+b9nB5ZHy/GugKh8lAsEeIs8h/USiAEUGuO0vNDEDTZEY1MkGhCSlMadmHZLlp7/2P28p4K1p8k20UcHwe7rMAtNk7nhdwk=
  skip_cleanup: true
  on: develop
  app:
    develop: saifu-api-stg

notifications:
  email: false
  slack:
    rooms:
      secure: "Wyo9iZxTrdfNMBMH8xbe5lxVhPCgkyPHQIOs83SskXxBk2L8VXEobwfrvPZmtmvaB9m7h+xNGwBg85KkbwrxlL8PIKTtLC41+rdSpYKhXXRrFcrWohoi1n7UKN2sOQ8yx6z+CAmrU3tCjaJuOcGbJoPWERsI+LBBEo14mFj91lKsdZeVYgnIyodbulMD28Xgwxd9F6b9SWPBPfF4QNtgk5ZNZE9NCEf9IGbveIingel4iABOIgT/dXJasgcCmgnqJH3tleQqvOxkePQ0kumYQO/+q8wVawBcCvjL29XbVtB0Oju6W3tiNshEzz4dmh/O4rJ4kSsslOhMjpTieciUVnLOZqHyQI0pYTbEgDll39/eM5guz/mKdbJvM+R/T3MWiz8ekAvpiDw5iQnZqzE294eKHmFS2SuGNttnFQWCQ2Bhm24Nv+XhUnbkvwxY+xhcAMTlRdEGyXuegsnL5hAk84RKc0PgmB05z3coNVEda5aOoFvSXrQdmv0B63nyjbmlMo3M3cpKLAx/2Ouc0uBTnC/7W/rQQcziRH9gp9nqiWJC9Lw/cfLfgA8D7QcXc9Ej/8LNZ9QSHXaL9Nd65iT3uPN1G4+wOvXHbDjVLb2tyBT47cdKiLN0y1ew4Xy7PKvj4Zdo/JoupyuGElo0RmOOhwQyMB/Y5WxJq68yY/G9604="
