language: python
python:
- 3.6.3
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE USER saifudevuser PASSWORD 'password';" -U postgres
- psql -c "ALTER USER saifudevuser CREATEDB;" -U postgres
- psql -c "CREATE DATABASE saifudev OWNER saifudevuser;" -U postgres
script:
- python manage.py migrate
- python manage.py test core
deploy:
  provider: heroku
  api_key:
    secure: fNQ/Ni1TRT0OZS8G4wV42ecI3wcG8CJ66uH2R9a5+nYFzK5nAVf3pkgz+PZJ/I1oSfaHc0PZlRaC7ldXzEc8crrSJA9BiAcSWbdW2qYVPTjMI37SVlvbV+NAQgWYdWp8zFtRnywHL07XrhaOh7u6kYLubZPoLGYGk/TRoVXL4URAsZnaa/L02bG33EcjdiUGtX82Sh3xeqyL+XBvdYcr6X8GM8GJ3pr/+1EPxg7NkD7XdK45+Q60LOBM1+FFtvWB1JV7YTMNm04gjUbobMV+CvmYEuRcO9sUL9cnXDn4B/5845JXWm3P3LtCoq0lyjyQMy823Ce7wKvVY463UtDp3ZN33/GxsjNAt39yK7JdqvP1ojpCuqQqiZguN2MwHwnOIqHEAeZveSahMqSEvVdyGEJ0lbCwllvuLDyZTgS2uROWMJT757VmaIPEIBk1BbccpWbVVJUj1n3EbX9xQnhtANSDm0mfRb1kYVYYr55akhiBSw6BnpYomSeW/JKWW5Mg4FJLbKOMVDMR9kaTkWDkphzERbO4LzAjTWXIx9xQ945KOyW4w6bFYBbbcKObRv2Loo6OgmGHsj9G+b9nB5ZHy/GugKh8lAsEeIs8h/USiAEUGuO0vNDEDTZEY1MkGhCSlMadmHZLlp7/2P28p4K1p8k20UcHwe7rMAtNk7nhdwk=
  skip_cleanup: true
  on: develop
  app:
    develop: saifu-api-stg
notifications:
  email: false
  slack:
    rooms:
      secure: KxK3XPjnO5w/gl4CGvswNHKNDQRFNV+o6f2dfX9RnLRV+lhnSOptPjdtPcd6/F/Kqms/McabNy59P/SarfvJ49oOU1DhZS4CmomDFPlZ878oPybEATLnJCaHFDI2BlphqN7T7WkjZZtiJvIp1pry/ujwuvYx7LBmdNAfN/r29pxgM5nfYUbDcjPOi/jvxrNV4kscQ8spjypNAOFp5ZOtXd/lQ33QoH2IAKmY2zJB6H3XyhxOqk1VPoMssaTg1/sX+RG4zsivDev79iRTrW19C8meEGCOg2e+VgMoQL/I5+lFCfEqNeU2am24/zhXVi8TgWrKrUqZAtSEKqhk+OytMdu9zl6J/Q2YlPNn2h/M8QJv0mya5mkmqvi/dKPJqCEOFCHME00pMPWhnvB/trTUP+aWXM/IYfWMRikov+msx/DzGv2fjIPrn8ktrKFFGi95TIfoH5/0sg0eQ9wHmekYuOoVI/w3XId5Lckh1ET/MDDtws4uZdUJ0QUNNgKL5vJSwMWdw5EqsWya000DsA84R6ax+N8GR/0TL120F2l71HVh5OiTVyTVcN4fflnsBrWEfAUriFsTJz6E7jUnu4KjxDuWcax9U4HISS+bSDOEcWGEoTP6iFtwzJO3GjdMzYDthzO9P/ChSfrAuUpPtyylrjLtcDvTKHxzq4inEakpwCA=
