# Generated by Django 2.0 on 2017-12-13 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCreditCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCreditCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('mCreditCategoryMain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MCreditCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MExpenseCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MExpenseCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('mExpenseCategoryMain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MExpenseCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MIncomeCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MIncomeCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('mIncomeCategoryMain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MIncomeCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSaifu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('initialBalance', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSaifuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('mCreditCategorySub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MCreditCategorySub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paymentRecipientName', models.CharField(blank=True, default='', max_length=30)),
                ('expenseDate', models.DateField()),
                ('note', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TExpenseDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('mExpenseCategorySub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MExpenseCategorySub')),
                ('mSaifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MSaifu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paymentSourceName', models.CharField(blank=True, default='', max_length=30)),
                ('incomeDate', models.DateField()),
                ('note', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIncomeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('mIncomeCategorySub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MIncomeCategorySub')),
                ('mSaifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MSaifu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TSaifuHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recordDate', models.DateField()),
                ('balance', models.BigIntegerField()),
                ('msaifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MSaifu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTransferBetweenAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transferDate', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('note', models.TextField()),
                ('fromSaifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromSaifu', to='core.MSaifu')),
                ('toSaifu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToSaifu', to='core.MSaifu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tcredit',
            name='tIncome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TIncome'),
        ),
        migrations.AddField(
            model_name='msaifu',
            name='mSaifuCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MSaifuCategory'),
        ),
    ]
