# Generated by Django 2.0 on 2018-01-11 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MAssetCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MAssetCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('m_asset_category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_asset_category_subs', to='core.MAssetCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCreditCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCreditCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('m_credit_category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_credit_category_subs', to='core.MCreditCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MExpenseCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MExpenseCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('m_expense_category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_expense_category_subs', to='core.MExpenseCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MIncomeCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MIncomeCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('m_income_category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_income_category_subs', to='core.MIncomeCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSaifuCategoryMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSaifuCategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('m_saifu_category_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_saifu_category_subs', to='core.MSaifuCategoryMain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TAssetEvaluate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('evaluate_date', models.DateField()),
                ('evaluated_amount', models.BigIntegerField()),
                ('note', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_asset_evaluates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('m_credit_category_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MCreditCategorySub')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_recipient_name', models.CharField(blank=True, default='', max_length=30)),
                ('expense_date', models.DateField()),
                ('note', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TExpenseDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('m_expense_category_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MExpenseCategorySub')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_expense_details', to=settings.AUTH_USER_MODEL)),
                ('t_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_expense_details', to='core.TExpense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('payment_source_name', models.CharField(blank=True, default='', max_length=30)),
                ('income_date', models.DateField()),
                ('note', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TIncomeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('m_income_category_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MIncomeCategorySub')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_income_details', to=settings.AUTH_USER_MODEL)),
                ('t_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_income_details', to='core.TIncome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTransferBetweenSaifu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('note', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTransferBetweenSaifuAndAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('note', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_transfer_between_saifu_and_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('current_capital_amount', models.BigIntegerField()),
                ('current_evaluated_amount', models.BigIntegerField()),
                ('m_asset_category_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MAssetCategorySub')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USaifu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('current_balance', models.BigIntegerField()),
                ('m_saifu_category_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MSaifuCategorySub')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saifus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ttransferbetweensaifuandasset',
            name='u_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_asset', to='core.UAsset'),
        ),
        migrations.AddField(
            model_name='ttransferbetweensaifuandasset',
            name='u_saifu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_saifu', to='core.USaifu'),
        ),
        migrations.AddField(
            model_name='ttransferbetweensaifu',
            name='from_u_saifu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_u_saifu', to='core.USaifu'),
        ),
        migrations.AddField(
            model_name='ttransferbetweensaifu',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_transfer_between_saifus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ttransferbetweensaifu',
            name='to_u_saifu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_u_saifu', to='core.USaifu'),
        ),
        migrations.AddField(
            model_name='tincomedetail',
            name='u_saifu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.USaifu'),
        ),
        migrations.AddField(
            model_name='texpensedetail',
            name='u_saifu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.USaifu'),
        ),
        migrations.AddField(
            model_name='tcredit',
            name='t_income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_credits', to='core.TIncome'),
        ),
        migrations.AddField(
            model_name='tassetevaluate',
            name='u_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_asset_evaluates', to='core.UAsset'),
        ),
    ]
