# Generated by Django 2.0 on 2017-12-12 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTransferBetweenAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('transferDate', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('note', models.TextField()),
                ('fromAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FromAccount', to='core.MAccount')),
                ('toAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ToAccount', to='core.MAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
